image: emediaorg/php:8.1-202303

pipelines:
    default:
        - step:
            name: Tests
            caches:
                - composer
            script:
                - composer install
                - vendor/bin/phpunit
